### ISSUE TITLE
NullPointerException after Idea launched

### ISSUE THREAD

**Issue by Kwaq** [andresdominguez/jsToolbox#10]
I'm getting NPE after lauching IDEA (15.0.2)

<pre>java.lang.NullPointerException
	at java.lang.String.replace(String.java:2180)
	at com.karateca.jstoolbox.torelated.GoToRelatedAction.goToFiles(GoToRelatedAction.java:113)
	at com.karateca.jstoolbox.torelated.GoToRelatedAction.actionPerformed(GoToRelatedAction.java:41)
	at com.karateca.jstoolbox.torelated.GoToViewAction.actionPerformed(GoToViewAction.java:8)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.c(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
</pre>

**Comment by andresdominguez** [comment]
Thank you for reporting the issue. I will try to reproduce it. Does it happen every time you try to go to a related file? What configuration did you use in the settings page?

**Comment by Kwaq** [comment]
As for the first question: probably not, because it happens sometimes and only after Idea startup. I did not relate it to particular file.
And here are my settings.
![js_toolbox](https://cloud.githubusercontent.com/assets/2842124/12474815/57b69cd0-c01e-11e5-8bca-89d498396e03.PNG)
